INSERT INTO answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (15, 'jo6337', NULL, NOW(), NOW()),
VALUES (19, 'advanced english studies', NULL, NOW(), NOW()),
VALUES (21, '5 months', NULL, NOW(), NOW()),
VALUES (23, 'about 4 months', NULL, NOW(), NOW()),
VALUES (26, 'B,D', {35,37}, NOW(), NOW()),
VALUES (29, 'seafood', NULL, NOW(), NOW()),
VALUES (30, 'tennis', NULL, NOW(), NOW()),
VALUES (31, 'keiko', NULL, NOW(), NOW()),
VALUES (32, 'keiko', NULL, NOW(), NOW()),
VALUES (34, 'keiko', NULL, NOW(), NOW()),
VALUES (35, 'keiko', NULL, NOW(), NOW()),
VALUES (36, 'keiko', NULL, NOW(), NOW()),
VALUES (37, 'keiko', NULL, NOW(), NOW()),
VALUES (38, 'keiko', NULL, NOW(), NOW()),
VALUES (39, 'keiko', NULL, NOW(), NOW()),
VALUES (40, 'keiko', NULL, NOW(), NOW()),
VALUES (41, 'keiko', NULL, NOW(), NOW()),
VALUES (42, 'keiko', NULL, NOW(), NOW()),
VALUES (43, 'keiko', NULL, NOW(), NOW()),
VALUES (45, 'keiko', NULL, NOW(), NOW()),
VALUES (46, 'keiko', NULL, NOW(), NOW()),
VALUES (47, 'keiko', NULL, NOW(), NOW()),
VALUES (48, 'keiko', NULL, NOW(), NOW()),
VALUES (53, 'keiko', NULL, NOW(), NOW()),
VALUES (55, 'keiko', NULL, NOW(), NOW()),
VALUES (57, 'keiko', NULL, NOW(), NOW()),
VALUES (59, 'keiko', NULL, NOW(), NOW()),
VALUES (61, 'keiko', NULL, NOW(), NOW()),
VALUES (62, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),
VALUES (7, 'keiko', NULL, NOW(), NOW()),

;
