INSERT INTO question_answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES 
(7, 'keiko', NULL, NOW(), NOW()),
(15, 'jo6337', NULL, NOW(), NOW()),
(19, 'advanced english studies', NULL, NOW(), NOW()),
(21, '5 months', NULL, NOW(), NOW()),
(23, 'about 4 months', NULL, NOW(), NOW()),
(26,  NULL, 35, NOW(), NOW()),
(26,  NULL, 37, NOW(), NOW()),
(29, 'seafood', NULL, NOW(), NOW()),
(30, 'tennis', NULL, NOW(), NOW()),
(31, 'take the train', NULL, NOW(), NOW()),
(32, 'this afternoon', NULL, NOW(), NOW()),
(34, '90 days', NULL, NOW(), NOW()),
(35, '30 pounds', NULL, NOW(), NOW()),
(36, 'confirm your nationality', NULL, NOW(), NOW()),
(37, 'page 13', NULL, NOW(), NOW()),
(38, 'currency form', NULL, NOW(), NOW()),
(39, 'tourist export form', NULL, NOW(), NOW()),
(40, 'bm276', NULL, NOW(), NOW()),
(41, 'international student card', NULL, NOW(), NOW()),
(42, '12', NULL, NOW(), NOW()),
(43, 'australian dollar', NULL, NOW(), NOW()),
(45, 'cashier', NULL, NOW(), NOW()),
(46, '£50', NULL, NOW(), NOW()),
(47, 'big department stores', NULL, NOW(), NOW()),
(48, 'jeans', NULL, NOW(), NOW()),
(53, '45 pounds', NULL, NOW(), NOW()),
(55, '75 pounds', NULL, NOW(), NOW()),
(57, '20 pounds', NULL, NOW(), NOW()),
(59, NULL, 41, NOW(), NOW()),
(59, NULL, 42, NOW(), NOW()),
(59, NULL, 43, NOW(), NOW()),
(61, NULL, 45, NOW(), NOW()),
(62, NULL, 49, NOW(), NOW()),
(63, NULL, 52, NOW(), NOW()),
(64, NULL, 58, NOW(), NOW()),
(65, NULL, 63, NOW(), NOW()),
(66, NULL, 66, NOW(), NOW()),
(67, NULL, 71, NOW(), NOW()),
(68, NULL, 72, NOW(), NOW()),
(69, NULL, 76, NOW(), NOW()),
(70, NULL, 80, NOW(), NOW());
